### ISSUE TITLE
USER / File Permission Error

### ISSUE THREAD

**Issue by khemarato** [meitar/jekyll-builder-for-github-pages-action#5]
I'm getting [a permissions error trying to touch Gemfile.lock](https://github.com/buddhist-uni/jekyll-dev-notes/runs/2607421882?check_suite_focus=true) on [a vanilla Jekyll blog](https://github.com/buddhist-uni/jekyll-dev-notes).  Any idea what I'm doing wrong?  😄  Thanks!

**Comment by fabacab** [comment]
Why are you trying to write `Gemfile.lock` as part of your CI/CD run? This file is a record of the exact Gems used to create your build and should be committed to source control along with your Gemfile and other source code. It is intended to be read by the CI/CD runner to recreate the intended build, not to be written to.

You should consider:

* [Using a version-pinned release](https://github.com/fabacab/jekyll-builder-for-github-pages-action#choosing-a-ref) of the GitHub Action, not `master`.
* Ensuring the version of Bundler running in your CI/CD job is the same version of Bundler you created the `Gemfile.lock` with (this is what [the pre-build hooks](https://github.com/fabacab/jekyll-builder-for-github-pages-action#pre_build_commands) are for).

**Comment by khemarato** [comment]
Ah, if that step is necessary, why make it an optional parameter?

**Comment by fabacab** [comment]
First, did that fix your issue?

> Ah, if that step is necessary, why make it an optional parameter?

Because it is not necessarily neccesary for everyone, but it might be (apparently is?) *for you* in *your* specific situation.

**Comment by fabacab** [comment]
I see you're not using this action anymore so I'm closing this issue.
